// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/CoulsonChen/GoApi/pkg/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateUsersService() (*UsersService, error) {
	gormDB := db.DBProvider()
	usersService := UsersServiceProvider(gormDB)
	return usersService, nil
}

// wire.go:

var ProviderSet = wire.NewSet(db.DBProvider, UsersServiceProvider, wire.Bind(new(IUsersService), new(*UsersService)))
