// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/CoulsonChen/GoApi/api"
	"github.com/CoulsonChen/GoApi/api/controllers"
	"github.com/CoulsonChen/GoApi/api/middlewares"
	"github.com/CoulsonChen/GoApi/pkg/config"
	"github.com/CoulsonChen/GoApi/pkg/db"
	"github.com/CoulsonChen/GoApi/pkg/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitHost() *route.Route {
	dbConfig := config.DbConfigProvider()
	gormDB := db.DBProvider(dbConfig)
	usersService := services.UsersServiceProvider(gormDB)
	jwtConfig := config.JwtConfigProvider()
	jwtService := services.JwtServiceProvider(jwtConfig)
	usersController := controllers.UsersControllerProvider(usersService, jwtService)
	jwtMiddleware := middlewares.JwtMiddlewareProvider(jwtService)
	routeRoute := route.RouteProvider(usersController, jwtMiddleware)
	return routeRoute
}

// wire.go:

var (
	controllerProviderSet = wire.NewSet(controllers.UsersControllerProvider)
	middlewareProviderSet = wire.NewSet(middlewares.JwtMiddlewareProvider)
	serviceProviderSet    = wire.NewSet(services.UsersServiceProvider, wire.Bind(new(services.IUsersService), new(*services.UsersService)), services.JwtServiceProvider, wire.Bind(new(services.IJwtService), new(*services.JwtService)))
	configProviderSet     = wire.NewSet(config.JwtConfigProvider, config.DbConfigProvider)
)

var providerSet = wire.NewSet(db.DBProvider, route.RouteProvider, controllerProviderSet,
	middlewareProviderSet,
	serviceProviderSet,
	configProviderSet,
)
