// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/CoulsonChen/GoApi/api"
	"github.com/CoulsonChen/GoApi/api/controllers"
	"github.com/CoulsonChen/GoApi/pkg/db"
	"github.com/CoulsonChen/GoApi/pkg/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitHost() *route.Route {
	gormDB := db.DBProvider()
	usersService := services.UsersServiceProvider(gormDB)
	usersController := controllers.UsersControllerProvider(usersService)
	routeRoute := route.RouteProvider(usersController)
	return routeRoute
}

// wire.go:

var (
	controllerProviderSet = wire.NewSet(controllers.UsersControllerProvider)
	// middlewareProviderSet = wire.NewSet()
	serviceProviderSet = wire.NewSet(services.UsersServiceProvider, wire.Bind(new(services.IUsersService), new(*services.UsersService)))
)

var providerSet = wire.NewSet(db.DBProvider, route.RouteProvider, controllerProviderSet,

	serviceProviderSet,
)
